openapi: 3.0.0
info:
  title: arXiv Search API
  description: An API that enables access to the arXiv.org API to search for academic papers.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /search:
    get:
      summary: Search for papers on arXiv.org based on the provided query.
      operationId: searchPapers
      parameters:
        - in: query
          name: query
          schema:
            type: string
          description: The search query.
          required: true
        - in: query
          name: maxResults
          schema:
            type: integer
          description: The maximum number of results to return.
          required: false
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      description: The title of the paper.
                    authors:
                      type: array
                      items:
                        type: string
                      description: A list of authors of the paper.
                    summary:
                      type: string
                      description: The summary or abstract of the paper.
                    link:
                      type: string
                      description: The URL to the PDF of the paper.
        '400':
          description: Bad request
        '500':
          description: Internal server error
